name: pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: [4.2]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: install
        run: npm install
      - name: lint
        run: npm run eslint:report
      - name: setup test env
        run: mongod --quiet --syslog & cp .env.test .env
      - name: test
        run: npm test
      - name: coverage
        run: npm run coverage
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: mocha-results
          path: mochawesome-report/
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  deploy:
    needs: test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: deployment
        if: ${{ github.event_name == 'push' &&  !contains(github.event.head_commit.message, '#skip')}}
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          checkstring: "ok"
          delay: 5
          rollbackonhealthcheckfailed: true

  tag:
    needs: deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' &&  !contains(github.event.head_commit.message, '#skip')}}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
